define: &kofi_donation_link https://ko-fi.com/intechgration

# NAVIGATION
navigation:
  - apply:
    label: Apply
    link: apply/
  - blog:
    label: Blog
    link: blog/
    dev: true
  - faq:
    label: FAQ
    link: faq/
  - donate:
    label: Donate
    link: *kofi_donation_link

# DONATION LINKS
donation_links:
  kofi: *kofi_donation_link
  paypal: ""
  buymeacoffe: ""
  patreon: ""

# FAQ PAGE:
faqs:
  - question: >-
      How do I enrol in the WDX 180° course?
    answer: >-
      You have to apply through our <a href="apply" target="_blank" class="font-bold underline">application form</a> and we will contact you with more details shortly after you've submitted your application.
  - question: >-
      Do I need prior coding experience to qualify?
    answer: >-
      Coding knowledge is not a prerequisite. However, it is considered a big plus. If you do have some experience, it will impact your acceptance decision and will give you a head start.
  - question: >-
      Will I be able to attend the course on-site?
    answer: >-
      The Core part of the program (2nd phase which happen to be the middle 3 months) will take place in-person in Kypseli. If you are a wheel-chair user, you will be attending the course remotely as unfortunately our space isn't accessible. However, we are on the lookout for an accessible space and we'll make an announcement once we find one.
  - question: >-
      Is it really free? Are there any hidden fees?
    answer: >-
      Our course is 100% free of charge and our curriculum is open source. There are no additional or hidden fees whatsoever. We're just a group of techies that wanna pay it forward😉.
  - question: >-
      Am I eligible for the course? (What qualifies me to get accepted into the
      course?)
    answer: >-
      Currently, our course is offered to underserved communities and groups
      that struggle due to discrimination, war, harsh social and economic
      conditions. Such groups include: refugees, asylum seekers, migrants,
      people with disabilities, former inmates, and other struggling groups that
      reside in countries within the following timezones: GMT+2, GMT+3, GMT+4.
  - question: Are all types of disabilities included in this course?
    answer: >-
      At this time, the course can be attended remotely by people with mobility
      impairments (such as wheelchair users, people with lower limb
      amputations). Soon we will have access to an accessible space, so that
      everyone can attend the courses in person. As we are unable to provide
      support for other types of impairments (e.g.blind,deaf and hard of
      hearing), we can only guarantee that a specific group of the disabled
      community can have a seamless experience of the course. However, if you
      are a disabled person, not in the aforementioned group, do not hesitate to
      contact us and maybe we can find a way!
  - question: How is the course structured?
    answer: >-
      The course is based on our open source Web Development X (WDX) curriculum.
      The course spans 9 months in total and <b>requires at least 4 to 5
      hours</b> of commitment (study and practice) on a daily basis.
  - question: What are the requirements for enrolling to the WDX180?
    answer: >-
      <ul class="list-disc pl-8"><li>Good english language skills</li><li>Basic computer
      skills</li><li>Computer equipped with a web camera and
      microphone <em>(If you will be attending our course in person, we provide access to a laptop and high-speed Internet connection)</em></li><li>Stable Internet connection</li></ul>
  - question: How much is the tuition fee?
    answer: >-
      There’s no tuition fee. Our curriculum and courses are and will always be
      open-source and tuition-free.
  - question: 'After registration, what next?'
    answer: >-
      We’ll get in touch with you, so we get to know each other and help you
      with the onboarding process
  - question: What happens if I don't pass the assessment?
    answer: >-
      You can still access and follow our curriculum for free or apply for one
      of our upcoming courses
  - question: When will the classes start?
    answer: 'Our next cohort starts October 2nd, 2023'
  - question: What is the duration of the course?
    answer: >-
      The course lasts for 9-months and specifically requires attendance for 180
      days.
  - question: Will I get a Diploma or Certificate at the end of the training?
    answer: >-
      We are going to provide you with a digital certificate of attendance so
      you might share it on your professional profiles such as LinkedIn, etc.
  - question: Do I need to have studied or have a background in tech to apply?
    answer: >-
      You should have basic computer skills and be fluent with the operating
      system (managing files and folders, configuring system settings, operating
      a browser, etc.)
  - question: Where will the classes take place?
    answer: >-
      If you are attending in person, you will be joining the 2nd trimester with
      us at the <a class="underline font-bold" href="https://www.facebook.com/ECHOHUBAthens/" target="_blank">EchoHub Athens</a>.
  - question: What will I learn in class for 9 months?
    answer: >-
      <span>You will learn:</span><ul class="list-disc pl-8"><li>How the Internet and the World Wide
      Web works </li><li>How to program in the languages of the Web (HTML, CSS,
      JavaScript) </li><li>CSS and JavaScript libraries and frameworks, such as
      Tailwind and React.js </li><li>Backend technologies (Node.js, Express,
      Databases, etc.)</li></ul>
